In [ ]:
import requests
import os

def download_github_folder(api_url, local_dir):
    """
    Recursively downloads files and folders from a GitHub repository using the REST API.
    """
    response = requests.get(api_url)
    
    if response.status_code != 200:
        print(f"Error: Could not fetch content from {api_url}")
        return

    items = response.json()

    # Ensure the local directory exists
    if not os.path.exists(local_dir):
        os.makedirs(local_dir)
        print(f"Created directory: {local_dir}")

    for item in items:
        if item['type'] == 'file':
            # Download individual files
            file_url = item['download_url']
            file_path = os.path.join(local_dir, item['name'])
            
            print(f"Downloading file: {item['name']}...")
            file_data = requests.get(file_url).content
            with open(file_path, 'wb') as f:
                f.write(file_data)
                
        elif item['type'] == 'dir':
            # Create sub-directory and go deeper (Recursion)
            new_api_url = item['url']
            new_local_dir = os.path.join(local_dir, item['name'])
            print(f"Entering folder: {item['name']}...")
            download_github_folder(new_api_url, new_local_dir)

# --- CONFIGURATION ---
# Target: https://github.com/hereandnowai/ml-data-hereandnowai/tree/main/data-for-eda
repo_owner = "hereandnowai"
repo_name = "ml-data-hereandnowai"
folder_path = "data-for-eda" 

# GitHub API URL format: https://api.github.com/repos/{owner}/{repo}/contents/{path}
api_base_url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/contents/{folder_path}"

# Start the download process into a local folder named 'data'
print("Starting bulk download from HERE AND NOW AI GitHub...")
download_github_folder(api_base_url, "data")
print("\nAll files and folders downloaded successfully!")

In [2]:
import numpy as np
import pandas as pd

In [7]:
covid_data = pd.read_csv("data/covid-data.csv")

In [8]:
covid_data.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,24/02/2020,5,5,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,25/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,26/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,27/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,28/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [10]:
covid_data = covid_data[['iso_code','continent','location','date','total_cases','new_cases']]

In [11]:
covid_data.head()

  iso_code continent     location        date  total_cases  new_cases
0      AFG      Asia  Afghanistan  24/02/2020            5          5
1      AFG      Asia  Afghanistan  25/02/2020            5          0
2      AFG      Asia  Afghanistan  26/02/2020            5          0
3      AFG      Asia  Afghanistan  27/02/2020            5          0
4      AFG      Asia  Afghanistan  28/02/2020            5          0

In [12]:
covid_data.dtypes

iso_code         str
continent        str
location         str
date             str
total_cases    int64
new_cases      int64
dtype: object

In [13]:
covid_data.shape

(5818, 6)

In [14]:
data_mean = np.mean(covid_data["new_cases"])
data_mean

np.float64(8814.365761430045)